In [1]:
import numpy as np

In [2]:
# 1. Create a 3x3 array filled with random integers between 0 and 10. Calculate the sum, mean, and standard deviation of the array.
arr = np.array(np.random.randn(3,3))

In [3]:
print(f"Sum: {arr.sum()} Mean: {arr.mean()} Standard deviation: {arr.std()}")

Sum: 0.4290826254514834 Mean: 0.047675847272387044 Standard deviation: 0.643130067304991


In [4]:
# 2. Create a 1D array of 10 elements and compute the cumulative sum of the elements.
arr1 = np.arange(10)

In [5]:
arr1.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [6]:
# 3. Generate two 2x3 arrays with random integers and perform element-wise addition, subtraction, multiplication, and division.
arr1_23 = np.array(np.random.randn(2,3))
arr2_23 = np.array(np.random.randn(2,3))
added_arr = np.add(arr1_23,arr2_23)
sub_arr = np.subtract(arr1_23,arr2_23)
mul_arr = np.multiply(arr1_23,arr2_23)
div_arr = np.divide(arr1_23,arr2_23)
print(f"Addition of two arrays: \n{added_arr}\nSubtraction of two arrays: \n{sub_arr}\nMultiplication of two arrays: \n{mul_arr}\nDivision of two arrays: \n{div_arr}")

Addition of two arrays: 
[[ 1.26199410e+00 -5.54393003e-01  4.04371128e-01]
 [-1.76058665e+00  6.55376451e-04  1.97052989e-01]]
Subtraction of two arrays: 
[[-0.48307701 -0.25782786  0.83385122]
 [-1.95077319 -1.72702378  1.28974948]]
Multiplication of two arrays: 
[[ 0.33981643  0.0602191  -0.13294796]
 [-0.17646267 -0.74565268 -0.40615596]]
Division of two arrays: 
[[  0.44635264   2.73876034  -2.88307275]
 [-19.51431439  -0.99924132  -1.36067287]]


In [7]:
# 4. Create a 4x4 identity matrix.
identity_matrix = np.array(np.identity(4))
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
# 5. Given an array a = np.array([5, 10, 15, 20, 25]), divide each element by 5 using broadcasting.
a = np.array([5, 10, 15, 20, 25])
b_a = a//5
print(*b_a)

1 2 3 4 5


In [9]:
# 6. Reshape a 1D array of 12 elements into a 3x4 matrix.
arr_1d = np.arange(12).reshape(3,4)
arr_1d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
# 7. Flatten a 3x3 matrix into a 1D array.
array_3x3 = np.arange(9).reshape(3,3)
flatten_arr = array_3x3.reshape(-1)
print(flatten_arr)

[0 1 2 3 4 5 6 7 8]


In [11]:
# 8. Stack two 3x3 matrices horizontally and vertically.
sample1_3x3 = np.array(np.random.randn(3,3))
sample2_3x3 = np.array(np.random.randn(3,3))
vstack_arr = np.vstack((sample1_3x3,sample2_3x3))
hstack_arr = np.hstack((sample1_3x3,sample2_3x3))
print(f"Vertically stacked arr: \n{vstack_arr}\nHorizontally stacked arr: \n{hstack_arr}")

Vertically stacked arr: 
[[-0.63906904 -1.01655724  0.28815036]
 [ 0.44578852  0.31955921 -0.86237869]
 [ 0.16886571 -0.33526242  0.63580038]
 [-0.2239296  -1.93860594  1.01273855]
 [ 0.52988328 -0.44302493  1.96847786]
 [ 0.52822876 -0.47205045  0.12257978]]
Horizontally stacked arr: 
[[-0.63906904 -1.01655724  0.28815036 -0.2239296  -1.93860594  1.01273855]
 [ 0.44578852  0.31955921 -0.86237869  0.52988328 -0.44302493  1.96847786]
 [ 0.16886571 -0.33526242  0.63580038  0.52822876 -0.47205045  0.12257978]]


In [12]:
# 9. Concatenate two arrays of different sizes along a new axis.
array_2x3 = np.array(np.random.randn(2,3))
array_3x2 = np.array(np.random.randn(2,2))
new_con_arr = np.concatenate((array_2x3,array_3x2),axis = 1)
new_con_arr

array([[ 0.41169053,  0.97300274,  1.47420021, -1.22447025,  0.09406811],
       [ 1.41029448,  0.6483358 , -0.2483643 ,  1.78103072,  1.11160934]])

In [13]:
# 10. Transpose a 3x2 matrix and then reshape it to have 3 rows and 2 columns.
arr_trans_3x2 = np.arange(6).reshape(3,2)
transposed_arr = np.transpose(arr_trans_3x2)
transposed_arr.reshape(3,2)

array([[0, 2],
       [4, 1],
       [3, 5]])

In [14]:
# 11. Given a 1D array of 15 elements, extract elements at positions 2 to 10 with a step of 2.
arr_15_elements= np.arange(15)
print(arr_15_elements[2:11:2])

[ 2  4  6  8 10]


In [15]:
# 12. Create a 5x5 matrix and extract the sub-matrix containing elements from rows 1 to 3 and columns 2 to 4.
arr_5x5 = np.arange(25).reshape(5,5)
print(arr_5x5)
print(arr_5x5[0:3,1:4])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


In [16]:
#  13. Replace all elements in a 1D array greater than 10 with the value 10.
arr_15_elements[arr_15_elements>10] = 10
arr_15_elements

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 10, 10, 10, 10])

In [17]:
# 14. Use fancy indexing to select elements from a 1D array at positions [0, 2, 4, 6].
fancy_arr = arr_15_elements[[0,2,4,6]]
fancy_arr

array([0, 2, 4, 6])

In [18]:
# 15. Create a 1D array of 10 elements and reverse it using slicing.
array_10 = np.arange(10)
array_10[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [19]:
# 16. Create a 3x3 matrix and add a 1x3 array to each row using broadcasting.
bc_3x3 = np.arange(9).reshape(3,3)
arr_3x1 = np.arange(3).reshape(1,3)
print(bc_3x3)
bc_3x3 = bc_3x3 + arr_3x1
print(bc_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


In [20]:
# 17. Multiply a 1D array of 5 elements by a scalar value using broadcasting.
arr_5 = np.arange(5)
arr_5 *= 3
print(arr_5)

[ 0  3  6  9 12]


In [21]:
# 18. Subtract a 3x1 column vector from a 3x3 matrix using broadcasting.
bc_3x3 = np.arange(9).reshape(3,3)
arr_3x1 = np.arange(3).reshape(3,1)
print(bc_3x3)
bc_3x3 -= arr_3x1
print(bc_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [2 3 4]
 [4 5 6]]


In [22]:
# 19. Add a scalar to a 3D array and demonstrate how broadcasting works across all dimensions.
arr_3d = np.arange(12).reshape(2,2,3)
print(arr_3d)
arr_3d += 3
print(arr_3d)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[[ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]]]


In [23]:
# 20. Create two arrays of shapes (4, 1) and (1, 5) and add them using broadcasting.
arr_4x1 = np.arange(4).reshape(4,1)
arr_1x5 = np.arange(5).reshape(1,5)
add_4x1_1x5 = arr_4x1 + arr_1x5

print(arr_4x1,'\n',arr_1x5,'\n',add_4x1_1x5)

[[0]
 [1]
 [2]
 [3]] 
 [[0 1 2 3 4]] 
 [[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


In [24]:
# 21. Compute the square root of each element in a 2D array using vectorized operations.
print(bc_3x3)
sqrt_arr = np.sqrt(bc_3x3)
print(sqrt_arr)

[[0 1 2]
 [2 3 4]
 [4 5 6]]
[[0.         1.         1.41421356]
 [1.41421356 1.73205081 2.        ]
 [2.         2.23606798 2.44948974]]


In [28]:
# 22. Calculate the dot product of two 1D arrays of size 5.
sample_1d = np.arange(5)
sample_1d1 = np.arange(5)
np.dot(sample_1d1,sample_1d)

30

In [26]:
# 23. Perform element-wise comparison of two 1D arrays and return an array of boolean values indicating where the first array has larger elements.
comparision = sample_1d > sample_1d1
print(comparision)

[False False False False False]


In [29]:
# 25. Create a 1D array of 100 random integers and compute the sum of all even numbers using vectorized operations.
arr_100 = np.arange(100)
print(np.sum(arr_100))

4950


In [30]:
# 26. Create a 3x3 matrix and find its determinant.
np.linalg.det(bc_3x3)

0.0

In [31]:
# 27. Given a 2x2 matrix, compute its inverse and verify by multiplying with the original matrix to obtain the identity matrix.
arr_2x2 = np.arange(4).reshape(2,2)
inv_arr_2x2 = np.linalg.inv(arr_2x2)
print(f"Normal:\n{arr_2x2}\nInverse:\n{inv_arr_2x2}\nMultiplication of Both:\n{arr_2x2@inv_arr_2x2}")

Normal:
[[0 1]
 [2 3]]
Inverse:
[[-1.5  0.5]
 [ 1.   0. ]]
Multiplication of Both:
[[1. 0.]
 [0. 1.]]


In [32]:
# 28. Calculate the eigenvalues and eigenvectors of a 2x2 matrix.
eigenvalues, eigenvector = np.linalg.eig(arr_2x2)
print(f"Eigen values:\n{eigenvalues}\nEigen Vectors:\n{eigenvector}")

Eigen values:
[-0.56155281  3.56155281]
Eigen Vectors:
[[-0.87192821 -0.27032301]
 [ 0.48963374 -0.96276969]]


In [33]:
# 29. Solve the system of linear equations 2x + 3y = 5 and 4x + 6y = 10 using NumPy.
equations_left = np.array([[2,3],
                       [4,6]])
equations_right = np.array([[5],[10]])
print(f"Solving linear equations using numpy\n{np.linalg.pinv(equations_left)@equations_right}")

Solving linear equations using numpy
[[0.76923077]
 [1.15384615]]


In [34]:
# 30. Perform Singular Value Decomposition (SVD) on a 3x3 matrix and reconstruct the original matrix using the SVD components.
U,S,Vt = np.linalg.svd(bc_3x3)
print(bc_3x3)
print(f"U:{U}\nS:{S}\nVt:{Vt}")

[[0 1 2]
 [2 3 4]
 [4 5 6]]
U:[[-0.18984612  0.89291197  0.40824829]
 [-0.51337419  0.26415956 -0.81649658]
 [-0.83690226 -0.36459285  0.40824829]]
S:[1.04731645e+01 1.14578549e+00 3.19043195e-16]
Vt:[[-0.41767294 -0.56472711 -0.71178129]
 [-0.81171587 -0.12006923  0.57157741]
 [-0.40824829  0.81649658 -0.40824829]]
